const countryCodes = [
  { name: "United States", code: "US", dialCode: "1" },
  { name: "United Kingdom", code: "GB", dialCode: "44" },
  { name: "Kenya", code: "KE", dialCode: "254" },
  { name: "Canada", code: "CA", dialCode: "1" },
  { name: "Australia", code: "AU", dialCode: "61" },
  { name: "Germany", code: "DE", dialCode: "49" },
  { name: "France", code: "FR", dialCode: "33" },
  { name: "Japan", code: "JP", dialCode: "81" },
  { name: "China", code: "CN", dialCode: "86" },
  { name: "India", code: "IN", dialCode: "91" },
  { name: "Brazil", code: "BR", dialCode: "55" },
  { name: "South Africa", code: "ZA", dialCode: "27" },
  { name: "Mexico", code: "MX", dialCode: "52" },
  { name: "Russia", code: "RU", dialCode: "7" },
  { name: "South Korea", code: "KR", dialCode: "82" },
  { name: "Italy", code: "IT", dialCode: "39" },
  { name: "Spain", code: "ES", dialCode: "34" },
  { name: "Netherlands", code: "NL", dialCode: "31" },
  { name: "Switzerland", code: "CH", dialCode: "41" },
  { name: "Sweden", code: "SE", dialCode: "46" },
  { name: "Norway", code: "NO", dialCode: "47" },
  { name: "Denmark", code: "DK", dialCode: "45" },
  { name: "Finland", code: "FI", dialCode: "358" },
  { name: "Belgium", code: "BE", dialCode: "32" },
  { name: "Austria", code: "AT", dialCode: "43" },
  { name: "Portugal", code: "PT", dialCode: "351" },
  { name: "Greece", code: "GR", dialCode: "30" },
  { name: "Czech Republic", code: "CZ", dialCode: "420" },
  { name: "Poland", code: "PL", dialCode: "48" },
  { name: "Romania", code: "RO", dialCode: "40" },
  { name: "Bulgaria", code: "BG", dialCode: "359" },
  { name: "Hungary", code: "HU", dialCode: "36" },
  { name: "Slovakia", code: "SK", dialCode: "421" },
  { name: "Slovenia", code: "SI", dialCode: "386" },
  { name: "Lithuania", code: "LT", dialCode: "370" },
  { name: "Latvia", code: "LV", dialCode: "371" },
  { name: "Estonia", code: "EE", dialCode: "372" },
  { name: "Croatia", code: "HR", dialCode: "385" },
  { name: "Slovenia", code: "SI", dialCode: "386" },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "387" },
  { name: "North Macedonia", code: "MK", dialCode: "389" },
  { name: "Albania", code: "AL", dialCode: "355" },
  { name: "Montenegro", code: "ME", dialCode: "382" },
  { name: "Serbia", code: "RS", dialCode: "381" },
  { name: "Kosovo", code: "XK", dialCode: "383" },
  { name: "Tanzania", code: "TZ", dialCode: "255" },
  { name: "Uganda", code: "UG", dialCode: "256" },
  { name: "Zambia", code: "ZM", dialCode: "260" },
  { name: "Zimbabwe", code: "ZW", dialCode: "263" },
  { name: "Namibia", code: "NA", dialCode: "264" },
  { name: "Madagascar", code: "MG", dialCode: "261" },
  { name: "Mauritius", code: "MU", dialCode: "230" },
  { name: "Reunion", code: "RE", dialCode: "262" },
  { name: "Mayotte", code: "YT", dialCode: "269" },
  { name: "Comoros", code: "KM", dialCode: "269" },
  { name: "Seychelles", code: "SC", dialCode: "248" },
  { name: "Mauritania", code: "MR", dialCode: "222" },
  { name: "Cape Verde", code: "CV", dialCode: "238" },
  { name: "Guinea-Bissau", code: "GW", dialCode: "245" },
  { name: "Sao Tome and Principe", code: "ST", dialCode: "239" },
  { name: "Liberia", code: "LR", dialCode: "231" },
  { name: "Guinea", code: "GN", dialCode: "224" },
  { name: "Togo", code: "TG", dialCode: "228" },
  { name: "Benin", code: "BJ", dialCode: "229" },
  { name: "Burkina Faso", code: "BF", dialCode: "226" },
  { name: "Mali", code: "ML", dialCode: "223" },
  { name: "Senegal", code: "SN", dialCode: "221" },
  { name: "Niger", code: "NE", dialCode: "237" },
  { name: "Chad", code: "TD", dialCode: "235" },
  { name: "Central African Republic", code: "CF", dialCode: "236" },
  { name: "Congo, Republic of the", code: "CG", dialCode: "242" },
];

export default countryCodes;